apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where these resources will be deployed by Flux

# List of resource files to include
resources:
  - deployment.yml
  - service.yml

# Common labels to be applied to all resources managed by this Kustomization
commonLabels:
  app.kubernetes.io/name: my-nginx-app
  app.kubernetes.io/instance: my-nginx-instance-01
  app.kubernetes.io/version: "1.25"
  app.kubernetes.io/component: webserver
  app.kubernetes.io/part-of: my-application-suite
  app.kubernetes.io/managed-by: kustomize

# You can also specify images to ensure a specific version is used,
# or to change the registry.
images:
  - name: nginx # Original image name used in deployment.yaml
    newName: nginx # Can be changed to a different registry/path if needed
    newTag: 1.25.4 # Overrides the tag in deployment.yaml

# Example of adding a prefix to all resource names
# namePrefix: prod-

# Example of adding a suffix to all resource names
# nameSuffix: -v1

# Example of a simple patch (e.g., to increase replicas for a specific environment)
# This assumes you have a file named 'increase-replicas.yaml'
# patchesStrategicMerge:
#   - increase-replicas.yaml