apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: app-reg
  namespace: flux-system
spec:
  image: appreg.azurecr.io/<your-image-name>
  interval: 1m0s
  secretRef:
    name: acr-credentials